### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref   python 2.7

### ISSUE THREAD

**Issue by PyInstaller-w-F** [ptresearch/mmdetect#2]
I use windows 7 and python 2.7

When I used py2exe to make an .exe file I get the error;

Traceback (most recent call last):
File "mainpy", line 17, in <module>
File "main.py", line 17, in <module>
File "zipextimporter.pyc", line 82, in load_module
File "zipextimporter.pyc", line 82, in load_module
File "logging\__init__.pyc", line 26, in <module>
File "zipextimporter.pyc", line 82, in load_module
File "weakref.pyc", line 14, in <module>

ImportError: cannot import name _remove_dead_weakref

the same code could be used to make an .exe file in another computer so there is nothing wrong with the code. The minor environmental difference caused this problem. I used pycharm, python 2.7.10 and py2exe0.6.9. On another computer all other config are the same except using sublimetext instead of pycharm.
Could anyone please tell me how to fix that?

**Comment by ptresearch** [comment]
Thank you! You can find win32 binary at
https://github.com/ptresearch/mmdetect/commit/f933009983216c721d7bce3085266cfbf7d13db4
